export { default as Navigation } from "./Navigation";
export { default as StudentNavigation } from "./NavigationStudent";
export { default as AdminNavigation } from "./NavigationAdmin";
//export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as Admin } from "./Admin";
export { default as Student } from "./Student";
export { default as Khstudent } from "./Khstudent";
export {default as Login} from "./Login";
export {default as Adminbb} from "./Adminbb";
